### ISSUE TITLE
Can you recommend how to use bootstrap.bundle.min.js with this example ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [apgapg/vue_bootstrap_5_sample#2]
For a lot of bootstrap functionality, bootstrap.bundle.min.js is needed

e.g. Normally this can be done using

<script src="bootstrap/js/bootstrap.bundle.min.js"></script>

I can see that I have the bootstrap js filed installed  in  node_modules\bootstrap\dist\js  but I'm not sure whether its compatible with VueJS at all.
(And I know that its not being referneced by Vue at the moment)

I know that the previous versions of bootstrap were not directly compatible with VueJS, because they used JQuery, but as bootstrap 5 does not use JQuery, I'm hoping that the boostrap js bundle can be used.

Thanks

**Comment by apgapg** [comment]
The proper way to include bootstrap script is in https://github.com/apgapg/vue_bootstrap_5_sample/blob/master/src/scss/custom.scss 
or if you don't use scss try directly importing that script in 
https://github.com/apgapg/vue_bootstrap_5_sample/blob/master/src/main.js

You need to add minified version to this line
`@import "../../node_modules/bootstrap/scss/bootstrap";`

**Comment by rogerclarkmelbourne** [comment]
OK.

Do you mean add

@import "../../node_modules/bootstrap/scss/bootstrap";

here

https://github.com/apgapg/vue_bootstrap_5_sample/blob/master/src/main.js#L6

**Comment by apgapg** [comment]
Let me just try and add minified verion. I will share the exact changes then

**Comment by rogerclarkmelbourne** [comment]
OK. That would be great.. 
Thanks.

I'm a bit of a vue noob. I did a bit of dev using vue about 9 months ago, but that was the old version, and bootstrap was completely incompatible, unless I used bootstrap-vue, which seemed to be a bit of a hack.

So when I saw that bootstrap 5 no longer used jquery, I kinda hoped it would now be compatible with vue.

**Comment by apgapg** [comment]
The proper way to add bootstrap in scss is 
`@import "node_modules/bootstrap/scss/bootstrap";`
https://getbootstrap.com/docs/4.0/getting-started/theming/

And In this case we don't need minified version as during `npm build` it automatically take care of that

**Comment by apgapg** [comment]
In this project, bootstrap 5 is fully working with vue. You can try running it locally and confirm yourself.
A screenshot Is attached in README.md

**Comment by rogerclarkmelbourne** [comment]
Umm.  

Doesn't seem to have made any difference to me.

I just cloned the repo again, and pasted the Accordian example code (https://getbootstrap.com/docs/5.0/components/accordion/#flush)  from the bootstrap 5 docs into the HelloWorld.vue component, just below the bootstrap button

But the styles used don't seem to be getting picked up and none of the functionality works.

![image](https://user-images.githubusercontent.com/6146984/102464764-df494c80-40a0-11eb-88f1-5934ae39d401.png)

**Comment by apgapg** [comment]
Okay let me try to implement this. Must be some import missing in corresponding ts/js file

**Comment by rogerclarkmelbourne** [comment]
OK.

No worries..

**Comment by apgapg** [comment]
<img width="1552" alt="Screenshot 2020-12-17 at 4 19 12 PM" src="https://user-images.githubusercontent.com/13887407/102478473-a2229180-4083-11eb-8065-38b2f4329648.png">

If you look at the changes in this commit https://github.com/apgapg/vue_bootstrap_5_sample/commit/8bf87a49c18fb83e6e2a23f38b0c06660cdcdc8a
we were using alpha version before and also popper/core js was missing hence animation wasn't working. Also we need to include bootstrap in our main.js

Thanks for raising the issue. 
Please close if working correctly

**Comment by rogerclarkmelbourne** [comment]
Thankyou

I re-ran 
npm install

to install the latest bootstrap version files.

and 

npm audit fix 

because npm install warned of security problems

And its now working perfectly

Thankyou.
